//Profile
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const LOCATION_REPOSITORY = 'LOCATION_REPOSITORY';
export const GOOGLE_COORDINATES_REPOSITORY = 'GOOGLE_COORDINATES_REPOSITORY';
export const TRACKUSER_REPOSITORY = 'TRACKUSER_REPOSITORY';
export const USERHISTORY_REPOSITORY = 'USERHISTORY_REPOSITORY';

//Employment
export const EMPLOYEEDETAILS_REPOSITORY = 'EMPLOYEEDETAILS_REPOSITORY';
export const EMPLOYEEDETAILS_HISTORY_REPOSITORY =
  'EMPLOYEEDETAILS_HISTORY_REPOSITORY';

//Loan
export const LOANTRANSACTION_REPOSITORY = 'LOANTRANSACTION_REPOSITORY';

//EMI
export const EMIENTITY_REPOSITORY = 'EMIENTITY_REPOSITORY';
export const PARTIALENTITY_REPOSITORY = 'PARTIALENTITY_REPOSITORY';
export const ORDERENTITY_REPOSITORY = 'ORDERENTITY_REPOSITORY';
export const PAYMENT_ENTITY_REPOSITORY = 'PAYMENT_ENTITY_REPOSITORY';

//DISRBURSEMENT
export const DISBURSEMENTENTITY_REPOSITORY = 'DISBURSEMENTENTITY_REPOSITORY';

//UPI
export const UPIENTITY_REPOSITORY = 'UPIENTITY_REPOSITORY';

//Auto debit
export const MANUAL_AUTO_DEBIT_ENTITY_REPOSITORY =
  'MANUAL_AUTO_DEBIT_ENTITY_REPOSITORY';

//Media
export const CHAT_DOCUMENTENTITY_REPOSITORY = 'CHAT_DOCUMENTENTITY_REPOSITORY';

//NetBanking
export const USERNETBANKINGDETAILES_REPOSITORY =
  'USERNETBANKINGDETAILES_REPOSITORY';
export const BANKING_REPOSITORY = 'BANKING_REPOSITORY';

// NetHistory
export const NETHISTORY_REPOSITORY = 'NETHISTORY_REPOSITORY';

//Legal notice
export const LEGAL_NOTICE_REPOSITORY = 'LEGAL_NOTICE_REPOSITORY';

// Bank
export const TOTAL_BANK_REPOSITORY = 'TOTAL_BANK_REPOSITORY';

//Scoring
export const APPROVEDLOANAMOUNTFROMSALARY_REPOSITORY =
  'APPROVEDLOANAMOUNTFROMSALARY_REPOSITORY';
export const SALARYGRADE_REPOSITORY = 'SALARYGRADE_REPOSITORY';
export const SCORING_REPOSITORY = 'SCORING_REPOSITORY';
export const SCORECARD_REPOSITORY = 'SCORECARD_REPOSITORY';
export const SCORINGFIELD_REPOSITORY = 'SCORINGFIELD_REPOSITORY';
export const SCORINGFIELDGROUP_REPOSITORY = 'SCORINGFIELDGROUP_REPOSITORY';

//Admin
export const ADMIN_REPOSITORY = 'ADMIN_REPOSITORY';
export const CHANGE_LOGS_REPOSITORY = 'CHANGE_LOGS_REPOSITORY';
export const ADMINROLEMODULE_REPOSITORY = 'ADMINROLEMODULE_REPOSITORY';

//Contacts
export const CONTACT_DETAILS_REPOSITORY = 'CONTACT_DETAILS_REPOSITORY';

//Mandate
export const SUBSCRIPTION_ENTITY = 'SUBSCRIPTION_ENTITY';

//ESign
export const ESIGN_REPOSITORY = 'ESIGN_REPOSITORY';
export const ADMINLOGGERENTITY_REPOSITORY = 'ADMINLOGGERENTITY_REPOSITORY';
export const STAMP_REPOSITORY = 'STAMP_REPOSITORY';

// crm
export const CRMACTIVITY_REPOSITORY = 'CRMACTIVITY_REPOSITORY';

//Transactions
export const TRANSACTION_REPOSITORY = 'TRANSACTION_REPOSITORY';
// razorPayment
export const RAZORPAYMENT_REPOSITORY = 'RAZORPAYMENT_REPOSITORY';
